version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - backend
    ports:
      - "127.0.0.1:5432:5432" #use 172.17.0.1 if no network
#    expose:
#      - "5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "127.0.0.1:5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - backend
networks:
  backend:
volumes:
  local_pgdata:
  pgadmin-data:
